export function formatReviewComment(review: string): string {
  return [
    "## AI Review Bot",
    "",
    review,
    "",
    "---",
    "<sub>Generated by AI PR Reviewer and approved by a repository maintainer. Verify suggestions before applying them.</sub>",
  ].join("\\n");
}
